name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Statics and Dockerize
    runs-on: ubuntu-latest
    steps:
      # BEGIN - Enviroment setup
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      # END - Enviroment setup

      # BEGIN - npm build tasks
      - name: Build the app
        run: npm run build:prod

      # END - npm build tasks

      # BEGIN - Docker setup
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # END - Docker setup

      # BEGIN - Docker build
      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: ./Dockerfile
          push: true
          tags: rockspringa/e-health:facade-latest

      # END - Docker build
