name: Deploy

on:
  workflow_run:
    workflows: Build
    branches:
      - main

    types:
      - completed

jobs:
  deploy:
    name: Cloud Run Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # BEGIN - Enviroment setup
      - name: Checkout code
        uses: actions/checkout@v4

      # END - Enviroment setup

      # BEGIN - GCP setup
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_SA }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # END - GCP setup

      # BEGIN - Deploy
      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: ${{ secrets.GCP_SERVICE }}
          image: "rockspringa/e-health:${{ secrets.GCP_SERVICE }}-latest"

      # END - Deploy
